var password = "lol";

information = [
  "<br>",
  '<span class="color2">LOADING INFORMATION....</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  '<span class="command">BACKGROUND</span>         BACKGROUND OF SIERRA',
  '<span class="command">CLASSIFICATIONS</span>    LIST OF CLASSIFICATIONS',
  '<span class="command">DEPARTMENTS</span>        LIST OF DEPARTMENTS',
  '<span class="command">CLEARANCES</span>         LIST OF CLEARANCES',
  "<br>",
  '<a href="https://discord.gg/DJvnv9C5Ub" class="command">DISCORD</a>            CLICK FOR DISCORD',
  "<br>",
  "<span class=\"color2\">TO RETURN TO THE HOMEPAGE, TYPE</span> <span class=\"command\">'HOME'</span><span class=\"color2\">.</span>",
  "<br>",
];

background = [
  "<br>",
  '<span class="color2">LOADING BACKGROUND....</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  "AFTER THE OUTBREAK OF VARIOUS VIRUSES WITHIN THE WORLD",
  "AN ORGANISATION CALLED SIERRA INDUSTRIES WAS FORMED WITH",
  "THE SOLE PURPOSE OF CONTAINING AND RESEARCHING THESE",
  "VIRUSES TO HALT FURTHER OUTBREAKS. WITH A VAST AMOUNT OF" ,
  "FUNDING BEING SENT FROM KEY GOVERNMENTS, SIERRA HAS",
  "STATIONED THEIR OPERATIONS ON AN ISLAND WEST OF",
  "THE UNITED STATES WHICH THEY REFER TO AS FACILITY NOMAD.",
  "<br>",
  "FACILITY NOMAD IS HIGHLY SECRETIVE AND ONLY ACCESSIBLE TO",
  "THOSE WITH THE CORRECT CLEARANCE LEVEL WITHIN SIERRA, ALL",
  "STAFF WHICH ARE PRESENT AT NOMAD GO THROUGH SERIOUS BACKGROUND",
  "CHECKS TO ENSURE THAT THEY ARE CAPABLE OF WORKING ON THE FACILITY.",
  "WITH THE HIGH LEVEL OF SECRECY REGARDING NOMAD THESE EMPLOYEES",
  "ARE AMONG THE BEST THE WORLD HAS TO OFFER, ENLISTED FROM VARYING",
  "AREAS OF THE WORLD AND SPECIALIZATIONS. ALL STAFF ARE PLACED INTO",  
  "A SIERRA DEPARTMENT UPON THEIR ARRIVAL ON NOMAD TO ENSURE A HIGH",
  "LEVEL OF ORGANISATION FOR THE OPERATIONS, EACH DEPARTMENT COMPLETES",
  "VARIOUS DUTIES TO BENEFIT THE ORGANISATION AND THEIR PROGRESS ON",
  "ALL RESEARCH CONDUCTED AT NOMAD.",
  "<br>",
  "AFTER RECENT UPRISINGS FROM TEST SUBJECTS, SIERRA BEGAN TO HIGHLY",
  "FORTIFY NOMAD TO ENSURE THAT ALL EXPERIMENTS ARE KEPT CONTAINED ON",
  "THE ISLAND, WITH THE HELP FROM THE SECURITY DEPARTMENT AND TASK FORCE",
  "DEPARTMENT OUTPOSTS ARE STATIONED WITHIN NOMAD TO ENSURE THAT ALL",
  "ACTIVITY ON THE ISLAND IS BEING MONITORED AS A METHOD OF REDUCING",
  "PANIC WITHIN THE WORLD.",
  "<br>",
  "<span class=\"color2\">TO RETURN TO THE HOMEPAGE, TYPE</span> <span class=\"command\">'HOME'</span><span class=\"color2\">.</span>",
  "<br>",
];

classifications = [
  "<br>",
  '<span class="color2">LOADING CLASSIFICATIONS....</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  "██████....",
  "....",
  "....",
  "<br>",
  "RED....",
  "....",
  "....",
  "<br>",
  "ORANGE....",
  "....",
  "....",
  "<br>",
  "YELLOW....",
  "....",
  "....",
  "<br>",
  "GREEN....",
  "....",
  "....",
  "<br>",
  "UNASSESSED....",
  "....",
  "....",
  "<br>",
  "<span class=\"color2\">TO RETURN TO THE HOMEPAGE, TYPE</span> <span class=\"command\">'HOME'</span><span class=\"color2\">.</span>",
  "<br>",
];

departments = [
  "<br>",
  '<span class="color2">LOADING DEPARTMENTS....</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  "BOARD OF DIRECTORS....",
  "....",
  "....",
  "<br>",
  "SECURITY DEPARTMENT....",
  "....",
  "....",
  "<br>",
  "RESEARCH DEPARTMENT....",
  "....",
  "....",
  "<br>",
  "TASK FORCE DEPARTMENT....",
  "....",
  "....",
  "<br>",
  "CHEMICAL INCIDENT DEPARTMENT....",
  "....",
  "....",
  "<br>",
  "MAINTENANCE DEPARTMENT....",
  "....",
  "....",
  "<br>",
  "<span class=\"color2\">TO RETURN TO THE HOMEPAGE, TYPE</span> <span class=\"command\">'HOME'</span><span class=\"color2\">.</span>",
  "<br>",
];

clearances = [
  "<br>",
  '<span class="color2">LOADING CLEARANCES....</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  "███████....",
  "....",
  "....",
  "<br>",
  "CLEARANCE 5....",
  "....",
  "....",
  "<br>",
  "CLEARANCE 4....",
  "....",
  "....",
  "<br>",
  "CLEARANCE 3....",
  "....",
  "....",
  "<br>",
  "CLEARANCE 2....",
  "....",
  "....",
  "<br>",
  "CLEARANCE 2....",
  "....",
  "....",
  "<br>",
  "CLEARANCE 1....",
  "....",
  "....",
  "<br>",
  "<span class=\"color2\">TO RETURN TO THE HOMEPAGE, TYPE</span> <span class=\"command\">'HOME'</span><span class=\"color2\">.</span>",
  "<br>",
];

archives = [
  "<br>",
  '<span class="color2">LOADING ARCHIVES....</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  '<span class="command">OPERATION</span>         LIST OF OPERATION ENTRIES',
  '<span class="command">FACILITY</span>          LIST OF FACILITY ENTRIES',
  '<span class="command">VIRUS</span>             LIST OF VIRUS ENTRIES',
  "<br>",
  "<span class=\"color2\">TO RETURN TO THE HOMEPAGE, TYPE</span> <span class=\"command\">'HOME'</span><span class=\"color2\">.</span>",
  "<br>",
];

operation = [
  "<br>",
  '<span class="color2">LOADING OPERATION ENTRIES....</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  'LIST OF OPERATION ENTRIES',
  "<br>",
  "<span class=\"color2\">TO RETURN TO THE HOMEPAGE, TYPE</span> <span class=\"command\">'HOME'</span><span class=\"color2\">.</span>",
  "<br>",
];

facility = [
  "<br>",
  '<span class="color2">LOADING FACILITY ENTRIES....</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  'LIST OF FACILITY ENTRIES',
  "<br>",
  "<span class=\"color2\">TO RETURN TO THE HOMEPAGE, TYPE</span> <span class=\"command\">'HOME'</span><span class=\"color2\">.</span>",
  "<br>",
];

virus = [
  "<br>",
  '<span class="color2">LOADING VIRUS ENTRIES....</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  'LIST OF VIRUS ENTRIES',
  "<br>",
  "<span class=\"color2\">TO RETURN TO THE HOMEPAGE, TYPE</span> <span class=\"command\">'HOME'</span><span class=\"color2\">.</span>",
  "<br>",
];

administrative = [
  "<br>",
  '<span class="color2">LOADING ADMINISTRATIVE SECTOR....</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  '<span class="command">VIRUS-001</span>          VIRUS LOG #001 - CLASSIFIED',
  "<br>",
  "<span class=\"color2\">TO RETURN TO THE HOMEPAGE, TYPE</span> <span class=\"command\">'HOME'</span><span class=\"color2\">.</span>",
  "<br>",
];

help = [
  "<br>",
  '<span class="color2">LOADING COMMANDS....</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  '<span class="command">INFORMATION</span>        INFORMATION ABOUT SIERRA',
  '<span class="command">ADMINISTRATIVE</span>     LIST OF ADMINISTRATIVE COMMANDS',
  '<span class="command">ARCHIVES</span>           LIST OF SIERRA ARCHIVES',
  "<br>",
  "<span class=\"color2\">TO RETURN TO THE HOMEPAGE, TYPE</span> <span class=\"command\">'HOME'</span><span class=\"color2\">.</span>",
  "<br>",
];

banner = [
  "<br>",
  '<span class="color2">COPYRIGHT 2022 (C) SIERRA INDUSTRIES. ALL RIGHTS RESERVED.</span>',
  "<br>",
  '<span class="color2">ACCESS GRANTED... SIERRA INDUSTRIES TERMINAL.</span>',
  "<br>",
  "<span class=\"color2\">FOR A LIST OF AVAILABLE COMMANDS, TYPE</span> <span class=\"command\">'HELP'</span><span class=\"color2\">.</span>",
  "<br>",
];
